# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiantes: 

### Crear un array a partir de una lista

In [1]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [2]:
#Código crear un array de ceros de tamaño 5x5

array_ceros = np.zeros((5,5))

print(array_ceros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [ ]:
#Código crear un array de unos de tamaño 3x3

array_unos = np.ones((2,3)) # Filas, Columnas

print(array_unos)

[[1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [ ]:
#Código rear un array con valores espaciados uniformemente de 0 a 9

array_linear = np.linspace(0, 9, 10)    # start: El valor inicial, stop: El valor final y num: (Opcional) Número de muestras a generar. (El valor predeterminado es 50.)

print(array_linear)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [12]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1

array_reto = np.linspace(0, 1, 6)

print(array_reto)

[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [19]:
array_salario = np.array([[5,4,2],[6,12,24]])
array_propinas = np.array([[6,4,9],[3,6,9]])


#Código realizar una suma, resta, multiplicación y división entre dos arrays (mientras tengan las mismas dimensiones)
suma = array_salario + array_propinas
resta = array_salario - array_propinas
multiplicacion = array_salario * array_propinas
division = array_salario / array_propinas


# Salida

print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)

La suma es:  [[11  8 11]
 [ 9 18 33]]
La resta es:  [[-1  0 -7]
 [ 3  6 15]]
La multiplicacion es:  [[ 30  16  18]
 [ 18  72 216]]
La division es:  [[0.83333333 1.         0.22222222]
 [2.         2.         2.66666667]]


In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [25]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media = np.mean(array_numeros)
print(f'La media aritmética es: {media}')

# Calcular la suma
suma = np.sum(array_numeros)
print(f'La sumatoria es: {suma}')

# Calcular el valor mínimo
minimo = np.min(array_numeros)
print(f'El valor mínimo es: {minimo}')

# Calcular el valor máximo
maximo = np.max(array_numeros)
print(f'El valor máximo es: {maximo}')


La media aritmética es: 3.0
La sumatoria es: 15
El valor mínimo es: 1
El valor máximo es: 5


In [27]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(2,3)
print(array_reshapeado)

[[1 2 3]
 [4 5 6]]


# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



# Caso #1 | Ejercicios reales o prácticos

In [34]:
# Preferencias de peliculas [Accion, Comedia, Drama]

kevin = np.array([7, 9, 2])

# Calcular la similitud de cada pelicula con los gustos de Kevin
pelicula_avatar = np.array([10, 1, 5])
pelicula_braveheart = np.array([8, 1, 7])

similitud_pelicula1 = np.dot(kevin,pelicula_avatar)
similitud_pelicula2 = np.dot(kevin,pelicula_braveheart)

print(f'La similitud entre las preferencias de Kevin y la película Avatar es de un: {similitud_pelicula1}%')
print(f'La similitud entre las preferencias de Kevin y la película Brave heart es de un: {similitud_pelicula2}%')

if similitud_pelicula1 > similitud_pelicula2:
    print('Basado en sus preferencias, le recomendamos la película Avatar.')
else:
    print('Basado en sus preferencias, le la película Brave heart.')

La similitud entre las preferencias de Kevin y la película Avatar es de un: 89%
La similitud entre las preferencias de Kevin y la película Brave heart es de un: 79%
Basado en sus preferencias, le recomendamos la película Avatar.


# Caso #2 | Estudio relación y corelación

In [38]:
import numpy as np
#Datos Tipo Cambio Dolar Ultimos 10 meses | IPC , metrica mensual


tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.70,109.33,108.85, 109.36,110.39,110.79])


#Calcular coeficiente de correlación
correlacion = np.corrcoef(tipo_cambio,ipc)[0,1]


print(f'Coeficiente de correlación: {correlacion:.2f}')

Coeficiente de correlación: 0.32


## Caso #3 | Estudio de horas comparado con notas

In [55]:
# Datos: Horas de estudio y Notas obtenidas

horas_estudio = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
notas_obtenidas = np.array([50, 55, 60, 63, 67, 72, 75, 78, 81, 85])

# Cálculo del crecimiento del promedio del puntuaje por hora de estudio
diferencias_notas = np.diff(notas_obtenidas) # Diferencias entre notas obtenidas, ejemplo 50-55 = 5 (primer número)
print(diferencias_notas)

promedio_diferencias = np.mean(diferencias_notas)
print(round(promedio_diferencias,2))

# Estimación del puntaje si estudio 12 horas

horas_estimadas = 12
##nota_estimada = (horas_estimadas - max(horas_estudio))   # Otro método
nota_estimada = round((((horas_estimadas - horas_estudio[-1]) * promedio_diferencias) + max(notas_obtenidas)), 2)
#** Paso 1: restar las horas estimadas y el valor máximo de horas de estudio
#** Paso 2: multiplicar el cálculo anterior por el promedio de las diferencias (variación entre notas)
#** Paso 3: sumar el cálculo anterior con el valor máximo de notas

nota_estimada_minima = round((((min(horas_estudio) - horas_estimadas) * promedio_diferencias) + min(notas_obtenidas)), 2)
nota_estimada_maxima = round((((max(horas_estudio) - horas_estimadas) * promedio_diferencias) + max(notas_obtenidas)), 2)

print(nota_estimada)
print(nota_estimada_minima)
print(nota_estimada_maxima)

[5 5 3 4 5 3 3 3 4]
3.89
92.78
7.22
77.22
